# Generated by Django 4.0.1 on 2022-02-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_is_salesman_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='User avatar'),
        ),
    ]
