# Generated by Django 4.0.1 on 2022-02-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='raiting',
            field=models.PositiveIntegerField(default=0, verbose_name='Rainting'),
        ),
    ]
