# Generated by Django 4.0.1 on 2022-02-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_raiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shop_background',
            field=models.CharField(default='#FFFFFF', max_length=255, verbose_name='Shop background'),
        ),
    ]
